### ISSUE TITLE
Release 3.0.0

### ISSUE THREAD

**Issue by ovidon83** [ovidon83/existinglearngit#1]
### Added

- [x]  - Add 'Headline' field to redeem code API for Zapier. [#1565]
- [x]  - Render 503 error page for Rack Timeout errors
- [x]  - Add ability for organisers to email all attendees. [#1083]
- [x]  - Added UI information saying "Session will be recorded for only 2 hours" on session recording checkbox [#1519]

### Removed

- [x]  - Removed graphs and versions filters from Admin for speed increase. [#1582]

### Changed

- [x]  - Added new backstage reset mechanism and refactored opentok broadcasting code [#1380]
- [x]  - Moved the help menu to the main navigation [1522](
- [x]  - Magic link CSV's are now processed in background. Organisers will be sent an email when processing is done. [#1559]

**Comment by ovidon83** [comment]
### CHANGELOG TEST RESULTS

RC Changelog Report | Test Result | Bug Details
-- | -- | --
Add 'Headline' field to redeem code API for Zapier | FAIL | #1565
Render 503 error page for Rack Timeout errors | PASS | #1576
Add ability for organisers to email all attendees | PASS | #1789
Added UI information saying "Session will be recorded for only 2 hours" on session recording checkbox | PASS | #2111



### END-TO-END TEST RESULTS


Task | Test Result | Bug Details
-- | -- | --
Create account::RegularGoogleFacebookLinkedIn | PASSED |  
Sign In::RegularGoogleFacebookLinkedIn | FAILED | #1576
User profile:: Create | PASSED |  
Create organisation | PASSED |  
Plans&Payments:: upgrade, downgrade, cancellation | FAILED | #1565
User:: Tabs(Home, Events, Connections, Profile, Security) | PASSED |  
User:: Find Events | FAILED | #1789

**Comment by ovidon83** [comment]
- [ ] Sign In::RegularGoogleFacebookLinkedIn bug:
Steps:
1
2
3
Screenshot: url

**Comment by ovidon83** [comment]
- [ ] Plans&Payments:: upgrade, downgrade, cancellation bug:
Steps:
1
2
3
Screenshot: url

**Comment by ovidon83** [comment]
- [ ] User:: Find Events bug:
Steps:
1
2
3
Screenshot: url

**Comment by ovidon83** [comment]
### CHANGELOG TEST RESULTS

RC Changelog Report | Test Result | Bug Details
-- | -- | --
Add 'Headline' field to redeem code API for Zapier | PASSED |
Render 503 error page for Rack Timeout errors | PASSED |
Add ability for organisers to email all attendees | PASSED |
Added UI information saying "Session will be recorded for only 2 hours" on session recording checkbox | PASSED |



### END-TO-END TEST RESULTS


Test Cases | Test Result | Bug Details
-- | -- | --
Create account::RegularGoogleFacebookLinkedIn | PASSED |  
Sign In::RegularGoogleFacebookLinkedIn | PASSED |
User profile:: Create | PASSED |  
Create organisation | PASSED |  
Plans&Payments:: upgrade, downgrade, cancellation | PASSED | 
User:: Tabs(Home, Events, Connections, Profile, Security) | PASSED |  
User:: Find Events | PASSED |
